backend:
  name: git-gateway
  branch: master

media_folder: 'uploads'
public_folder: '/uploads'

collections:
  - name: 'materials'
    label: 'Материалы'
    folder: 'materials'
    create: true
    slug: '{{slug}}'
    format: 'json'
    extension: 'json'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }

      - label: 'Категория'
        name: 'category'
        widget: 'select'
        options:
          - 'Гидроизоляционные материалы'
          - 'Добавки для бетона'
          - 'Подземное строительство'
          - 'Ремонтные составы и гротинговые растворы'
          - 'Напольные покрытия'

      - { label: 'Краткое описание', name: 'body', widget: 'text' }

      - { label: 'Область применения', name: 'application', widget: 'text' }
      - { label: 'Особенности и преимущества', name: 'features', widget: 'text' }
      - { label: 'Технические характеристики', name: 'technical', widget: 'text' }
      - { label: 'Дозировка и расход', name: 'dosage', widget: 'text' }
      - { label: 'Упаковка', name: 'packaging', widget: 'text' }
      - { label: 'Условия хранения', name: 'storage', widget: 'text' }
      - { label: 'Меры предосторожности', name: 'precautions', widget: 'text' }
      - { label: 'Контроль качества', name: 'control', widget: 'text' }
      - { label: 'Производитель', name: 'manufacturer', widget: 'string' }

      - label: 'PDF-файл'
        name: 'pdf'
        widget: 'file'
