name: Generate Materials Index

on:
  push:
    paths:
      - 'materials/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Установить зависимости
        run: npm install glob

      - name: Сгенерировать materials-index.json
        run: |
          node js/generate-index.js

      - name: Commit and push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Удаляем авторизационные заголовки GitHub, которые мешают токену работать
          git config --local --unset-all http.https://github.com/.extraheader || true

          # Перенастраиваем origin с токеном
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}

          git add data/materials-index.json
          git commit -m "⚙️ Автообновление materials-index.json" || echo "No changes"
          git push origin master
